import { SignUp } from "@clerk/nextjs";
 
export default function Page() {
  return (
    <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2">
      <SignUp />
    </div>
  )
}

export const metadata = {
    title: "Sign Up",
    description: "Generated by create next app",
  };